### ISSUE TITLE
Error: creating resource error Failed to load connector module "composer-connector-undefined" for connection type "undefined". Cannot find module 'composer-connector-undefined'

### ISSUE THREAD

**Issue by deltatrip** [hyperledger/composer-tools#128]
Hi, 

I have upgraded to composer v0.19.0 and now when trying to get it connect via node red I do receive the following error: 
`[error] [hyperledger-composer-out:carauction-network] Error: creating resource error Failed to load connector module "composer-connector-undefined" for connection type "undefined". Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'-Cannot find module 'composer-connector-undefined'
`

Is this the same issue as in this pull request? 
https://github.com/hyperledger/composer-tools/pull/126

**Comment by siler23** [comment]
I think this is the same issue addressed in the pull request. The node-red-composer-contrib@unstable now works with composer v0.19. Unfortunately, it is not labeled the latest build right now so you have to use the @unstable tag (i.e. npm install node-red-contrib-composer@unstable) to install this version instead of just npm install node-red-composer-contrib since that will install the older 0.0.10 version which only works with composer v0.16.x.

**Comment by deltatrip** [comment]
Thank you for pointing me to the unstable version. Wasn't sure about how to implement the changes. Now everything is working.
